recommendationBundle_getContent:
    path: /ez_recommendation/v1/content/{contentIdList}
    defaults:
        _controller: ez_recommendation.rest.controller.content:getContent
    methods: [GET]

recommendationBundle_getContentTypes:
    path: /ez_recommendation/v1/contenttypes/{contentTypeIdList}
    defaults:
        _controller: ez_recommendation.rest.controller.contenttype:getContentType
    methods: [GET]

recommendationBundle_downloadExportedContent:
    path: /ez_recommendation/v1/exportDownload/{filePath}
    defaults:
        _controller: ez_recommendation.rest.controller.export:downloadAction
    requirements:
        filePath: "[0-9/]+"
